### ISSUE TITLE
Opening torrent file from Explorer while client is open does nothing

### ISSUE THREAD

**Issue by litbeep** [luandersonn/TorrentClient-feedback#1]
Windows 22623.746
ByteStream Beta 0.0.35.0

If ByteStream is closed and I double-click a torrent file in the File Explorer, the app will launch and prompt me to configure the torrent as normal. However, if I try double-clicking a torrent file while the app is already open, nothing happens.

**Comment by luandersonn** [comment]
I'll investigate, I was able to reproduce the bug.

**Comment by luandersonn** [comment]
Please check version `0.0.37.x` and close the issue if the bug has been fixed.
