### ISSUE TITLE
Slow ui performance

### ISSUE THREAD

**Issue by dkostarnov** [luandersonn/TorrentClient-feedback#11]
Any menus open with friezes. You can also notice that after opening the menu, a shadow effect appears, then disappears and reappears.
https://youtu.be/_INAuSdqifI

**Comment by luandersonn** [comment]
@dkostarnov This problem has been addressed in the latest version of the Windows App SDK. I'm looking to update soon.

**Comment by luandersonn** [comment]
https://github.com/luandersonn/TorrentClient-feedback/assets/30560453/9ea48369-292e-4c41-b2d0-53404939b995

**Comment by dkostarnov** [comment]
> Gravando.2023-10-21.235107.mp4

Amazing 🔥🔥🔥

**Comment by luandersonn** [comment]
Update available (v1.0.16.0)
