### ISSUE TITLE
Opening multiple .torrent files from File Explorer opens multiple download window of only the first torrent

### ISSUE THREAD

**Issue by ruulr** [luandersonn/TorrentClient-feedback#13]
How to reproduce the bug:
Select multiple .torrent files from File Explorer and press Enter/Return. (example1.torrent, example2.torrent, example3.torrent)

Expectation:
Each of the files spawn their own 'Download' window.

What actually happens:
3 windows spawn but they're all example1.torrent 'Download' window.

**Comment by luandersonn** [comment]
Thanks. I was able to reproduce.

**Comment by luandersonn** [comment]
This bug has been fixed in version `1.0.0`, can you close the issue?
