### ISSUE TITLE
Double clicking a downloaded file doesn't open it

### ISSUE THREAD

**Issue by Sventra** [luandersonn/TorrentClient-feedback#2]
Let's say I just downloaded an .mp4 file, or in my case, an .mkv video, when I double click the torrent from the home it opens the files list of said torrent, but when I double click the file I just downloaded it won't open it, I need to open the folder the file was downloaded in through right clicking it and opening the folder

Pretty minor but something I would care about in the long run

**Comment by luandersonn** [comment]
Thank you, @Sventra. This feature will be available in the next version

**Comment by luandersonn** [comment]
Please, check out the `v0.0.43`
