### ISSUE TITLE
Portuguese (Portugal) translation

### ISSUE THREAD

**Issue by esibruti** [luandersonn/TorrentClient-feedback#20]
The application is very practical and easy to use, however I would like to introduce the language of Portuguese of Portugal to the application, since there are differences between the Portuguese of Portugal and the Portuguese of Brazil.

**Comment by luandersonn** [comment]
Adicionei [PT-PT](https://github.com/luandersonn/TorrentClient-feedback/blob/277614486da69f478dd4c5659c600aad278fdce6/translations/TorrentClient.pt-PT.xlf) a lista de arquivos

**Comment by luandersonn** [comment]
Adicionado na última versão
