### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by kamez104** [luandersonn/TorrentClient-feedback#24]
Hi, I love this app, but I would love it even more if I could use it in my native language. I have some free time on my hands and would like to translate the app

**Comment by luandersonn** [comment]
I will upload the translation file very soon. Can you tell me the language code? (Example, en-us)

**Comment by kamez104** [comment]
pl-PL

**Comment by luandersonn** [comment]
@kamez104 translations/TorrentClient.pl-PL.xlf added
