### ISSUE TITLE
Incorrect speed limit header in options when adding torrent file

### ISSUE THREAD

**Issue by aleks-ko89** [luandersonn/TorrentClient-feedback#25]
There is a speed limit option in the option when adding a file, but they are both called ‘**Download** speed limit’
![TorrentClient](https://github.com/luandersonn/TorrentClient-feedback/assets/2191515/36fbd89d-bd4f-4557-af29-abe67b77b33b)
Sorry for russian interface screenshot

**Comment by luandersonn** [comment]
Thanks @aleks-ko89 !

**Comment by luandersonn** [comment]
Thanks @aleks-ko89, it looks like the two headers refer to the same string.

Updated :)

![image](https://github.com/luandersonn/TorrentClient-feedback/assets/30560453/375f21ba-2485-4cfa-80de-b3c207795e97)

![archlinux-2022 09 03-x86_64 iso - ByteStream_b1](https://github.com/luandersonn/TorrentClient-feedback/assets/30560453/eb210ff8-9562-4c1f-b258-0c27e7dceb22)

**Comment by luandersonn** [comment]
Update available `1.0.50`
