### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by esibruti** [luandersonn/TorrentClient-feedback#3]
Windows 11 Home 22621.674

I didn't check this functionality but if it doesn't exist, it would be interesting to add notifications, that is, if the transfer ends or there is an error and the program is minimized, indicate in windows notifications that the transfer has ended or that an error has occurred.

There could be some setting to enable and disable this functionality if possible.

**Comment by luandersonn** [comment]
Work In Progress

**Comment by luandersonn** [comment]
Update (WIP)
![image](https://user-images.githubusercontent.com/30560453/197405956-082bdee3-9348-4b85-9381-9d09a0a3fa7f.png)

**Comment by esibruti** [comment]
Wow, it's really fantastic, it's going to be really amazing to have this notifications function, it's going to be really useful.

**Comment by luandersonn** [comment]
Notifications feature is rolling out for public beta
