### ISSUE TITLE
Closing the app will force every torrent to stop seeding

### ISSUE THREAD

**Issue by Sventra** [luandersonn/TorrentClient-feedback#6]
The app should follow how other clients work so it should still be seeding the torrent after restarting the app, more seeders are always needed and the default behavior should keep them seeding the torrents unless Windows settings state that the current connection is a metered one

**Comment by luandersonn** [comment]
Thank you @Sventra. In the next version, the state of the torrent will persist after restarting the app.

**Comment by luandersonn** [comment]
This feature is rolling out for public beta
